##generate plot4 as png file
png(file="plot4.png")
par(mfrow = c(2,2), mar = c(5,4,2,1))
plot(datetime,data$Global_active_power, xlab="", ylab="Global Active Power", type="n")
lines(datetime, data$Global_active_power, lwd=1)
plot(datetime, data$Voltage, ylab = "Voltage", type = "n")
lines(datetime, data$Voltage, lwd=1)
plot (datetime, data$Sub_metering_1, xlab="", ylab = "Energy sub metering", type ="n")
lines(datetime, data$Sub_metering_1, lwd=1, col="black")
lines(datetime, data$Sub_metering_2, lwd=1, col="red")
lines(datetime, data$Sub_metering_3, lwd=1, col="blue")
legend("topright", lty = 1, col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty = "n")
plot(datetime, data$Global_reactive_power, type ="n")
lines(datetime, data$Global_reactive_power)
dev.off()